# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestHCM():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_login(self):
    self.driver.get("http://192.168.6.103:7070/HCM/")
    self.driver.set_window_size(1366, 728)
    self.driver.find_element(By.CSS_SELECTOR, ".form-group:nth-child(1) > .form-control").click()
    self.driver.find_element(By.XPATH, "//input").send_keys("Admin")
    self.driver.find_element(By.CSS_SELECTOR, ".form-group:nth-child(2) > .form-control").click()
    self.driver.find_element(By.XPATH, "//div[2]/input").send_keys("Newpass2@")
    self.driver.find_element(By.CSS_SELECTOR, ".ng-input > input").click()
    self.driver.find_element(By.XPATH, "//span[contains(.,\'VS001\')]").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
  
  def test_modifyTheGradeMasterData(self):
    self.driver.get("http://192.168.6.103:7070/HCM/")
    self.driver.set_window_size(1366, 728)
    self.driver.find_element(By.CSS_SELECTOR, ".form-group:nth-child(1) > .form-control").click()
    self.driver.find_element(By.XPATH, "//input").send_keys("Admin")
    self.driver.find_element(By.CSS_SELECTOR, ".form-group:nth-child(2) > .form-control").click()
    self.driver.find_element(By.XPATH, "//div[2]/input").send_keys("Newpass2@")
    self.driver.find_element(By.CSS_SELECTOR, ".ng-input > input").click()
    self.driver.find_element(By.XPATH, "//span[contains(.,\'VS001\')]").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
    element = self.driver.find_element(By.ID, "dropdownBasic2")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".has-sub:nth-child(2) > .ng-tns-c152-3 > .menu-title").click()
    self.driver.find_element(By.CSS_SELECTOR, ".ng-tns-c152-3:nth-child(2) > .menu-content > .ng-tns-c152-3:nth-child(1) .menu-title").click()
    self.driver.find_element(By.CSS_SELECTOR, ".ng-star-inserted:nth-child(2) > .text-center .fa").click()
    self.driver.find_element(By.XPATH, "//div[3]/div/input").click()
    self.driver.find_element(By.XPATH, "//div[3]/div/input").send_keys("CO BC")
    self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()
  
  def test_modifyTheDesignationMasterData(self):
    self.driver.get("http://192.168.6.103:7070/HCM/")
    self.driver.set_window_size(1366, 728)
    self.driver.find_element(By.CSS_SELECTOR, ".form-group:nth-child(1) > .form-control").click()
    self.driver.find_element(By.XPATH, "//input").send_keys("Admin")
    self.driver.find_element(By.CSS_SELECTOR, ".form-group:nth-child(2) > .form-control").click()
    self.driver.find_element(By.XPATH, "//div[2]/input").send_keys("Newpass2@")
    self.driver.find_element(By.CSS_SELECTOR, ".ng-input > input").click()
    self.driver.find_element(By.XPATH, "//span[contains(.,\'VS001\')]").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
    self.driver.find_element(By.CSS_SELECTOR, ".has-sub:nth-child(2) > .ng-tns-c152-3 > .menu-title").click()
    self.driver.find_element(By.CSS_SELECTOR, ".ng-tns-c152-3:nth-child(2) > .menu-content > .ng-tns-c152-3:nth-child(2) .menu-title").click()
    self.driver.find_element(By.CSS_SELECTOR, ".text-left:nth-child(1) button").click()
    self.driver.find_element(By.XPATH, "//div[4]/div/select").click()
    dropdown = self.driver.find_element(By.XPATH, "//div[4]/div/select")
    dropdown.find_element(By.XPATH, "//option[. = 'Self']").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()
  
  def test_modifyTheDepartmentMasterData(self):
    self.driver.get("http://192.168.6.103:7070/HCM/")
    self.driver.set_window_size(1366, 728)
    self.driver.find_element(By.CSS_SELECTOR, ".form-group:nth-child(1) > .form-control").click()
    self.driver.find_element(By.XPATH, "//input").send_keys("Admin")
    self.driver.find_element(By.CSS_SELECTOR, ".form-group:nth-child(2) > .form-control").click()
    self.driver.find_element(By.XPATH, "//div[2]/input").send_keys("Newpass2@")
    self.driver.find_element(By.CSS_SELECTOR, ".ng-input > input").click()
    self.driver.find_element(By.XPATH, "//span[contains(.,\'VS001\')]").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
    self.driver.find_element(By.XPATH, "//span[contains(.,\'Personal Information Systems\')]").click()
    self.driver.find_element(By.XPATH, "//span[contains(.,\'Department Master\')]").click()
    self.driver.find_element(By.XPATH, "//button[contains(.,\'Modify\')]").click()
    self.driver.find_element(By.CSS_SELECTOR, ".text-left:nth-child(1) .fa").click()
    self.driver.find_element(By.XPATH, "//td[3]/input").click()
    self.driver.find_element(By.XPATH, "//td[3]/input").send_keys("22")
    self.driver.find_element(By.CSS_SELECTOR, ".btn-md:nth-child(2)").click()
  
  def test_modifyTheDepartmentSectionMasterData(self):
    self.driver.get("http://192.168.6.103:7070/HCM/")
    self.driver.set_window_size(1366, 728)
    self.driver.find_element(By.CSS_SELECTOR, ".form-group:nth-child(1) > .form-control").click()
    self.driver.find_element(By.XPATH, "//input").send_keys("Admin")
    self.driver.find_element(By.CSS_SELECTOR, ".form-group:nth-child(2) > .form-control").click()
    self.driver.find_element(By.XPATH, "//div[2]/input").send_keys("Newpass2@")
    self.driver.find_element(By.CSS_SELECTOR, ".ng-input > input").click()
    self.driver.find_element(By.XPATH, "//span[contains(.,\'VS001\')]").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
    self.driver.find_element(By.CSS_SELECTOR, ".has-sub:nth-child(2) > .ng-tns-c152-3 > .menu-title").click()
    self.driver.find_element(By.CSS_SELECTOR, ".ng-tns-c152-3:nth-child(2) > .menu-content > .ng-tns-c152-3:nth-child(4) .menu-title").click()
    self.driver.find_element(By.CSS_SELECTOR, ".ng-star-inserted:nth-child(1) > .text-center .fa").click()
    self.driver.find_element(By.XPATH, "//td[2]/input").click()
    self.driver.find_element(By.XPATH, "//td[2]/input").send_keys("12")
    self.driver.find_element(By.CSS_SELECTOR, ".btn-md:nth-child(2)").click()
  
  def test_modifyTheTeamMasterData(self):
    self.driver.get("http://192.168.6.103:7070/HCM/")
    self.driver.set_window_size(1366, 728)
    self.driver.find_element(By.CSS_SELECTOR, ".form-group:nth-child(1) > .form-control").click()
    self.driver.find_element(By.XPATH, "//input").send_keys("Admin")
    self.driver.find_element(By.CSS_SELECTOR, ".form-group:nth-child(2) > .form-control").click()
    self.driver.find_element(By.XPATH, "//div[2]/input").send_keys("Newpass2@")
    self.driver.find_element(By.CSS_SELECTOR, ".ng-input > input").click()
    self.driver.find_element(By.XPATH, "//span[contains(.,\'VS001\')]").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
    self.driver.find_element(By.CSS_SELECTOR, ".has-sub:nth-child(2) > .ng-tns-c152-3 > .menu-title").click()
    self.driver.find_element(By.LINK_TEXT, "Team Master").click()
    self.driver.find_element(By.CSS_SELECTOR, ".ng-star-inserted:nth-child(2) > .text-center .fa").click()
    self.driver.find_element(By.XPATH, "//div[2]/div/input").click()
    self.driver.find_element(By.XPATH, "//div[2]/div/input").send_keys("ANIL KUMAR")
    self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()
  
  def test_modifyTheLeaveTypeData(self):
    self.driver.get("http://192.168.6.103:7070/HCM/")
    self.driver.set_window_size(1366, 728)
    self.driver.find_element(By.CSS_SELECTOR, ".form-group:nth-child(1) > .form-control").click()
    self.driver.find_element(By.XPATH, "//input").send_keys("Admin")
    self.driver.find_element(By.CSS_SELECTOR, ".form-group:nth-child(2) > .form-control").click()
    self.driver.find_element(By.XPATH, "//div[2]/input").send_keys("Newpass2@")
    self.driver.find_element(By.CSS_SELECTOR, ".ng-input > input").click()
    self.driver.find_element(By.XPATH, "//span[contains(.,\'VS001\')]").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
    self.driver.find_element(By.XPATH, "//span[contains(.,\'Personal Information Systems\')]").click()
    self.driver.find_element(By.LINK_TEXT, "Leave Type Master").click()
    self.driver.find_element(By.CSS_SELECTOR, ".ng-star-inserted:nth-child(1) > .text-center > button").click()
    self.driver.find_element(By.CSS_SELECTOR, ".col-lg-3:nth-child(4) .floating-select").click()
    dropdown = self.driver.find_element(By.XPATH, "//div[4]/div/select")
    dropdown.find_element(By.XPATH, "//option[. = 'No']").click()
    self.driver.find_element(By.CSS_SELECTOR, ".col-lg-3:nth-child(6) .floating-select").click()
    dropdown = self.driver.find_element(By.CSS_SELECTOR, ".col-lg-3:nth-child(6) .floating-select")
    dropdown.find_element(By.XPATH, "//option[. = 'End of the Period']").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()
  
  def test_modifyTheLeaveRulesData(self):
    self.driver.get("http://192.168.6.103:7070/HCM/")
    self.driver.set_window_size(1366, 728)
    self.driver.find_element(By.CSS_SELECTOR, ".form-group:nth-child(1) > .form-control").click()
    self.driver.find_element(By.XPATH, "//input").send_keys("Admin")
    self.driver.find_element(By.CSS_SELECTOR, ".form-group:nth-child(2) > .form-control").click()
    self.driver.find_element(By.XPATH, "//div[2]/input").send_keys("Newpass2@")
    self.driver.find_element(By.CSS_SELECTOR, ".ng-input > input").click()
    self.driver.find_element(By.XPATH, "//span[contains(.,\'VS001\')]").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
    self.driver.find_element(By.LINK_TEXT, "Personal Information Systems").click()
    self.driver.find_element(By.LINK_TEXT, "Leave Rules").click()
    self.driver.find_element(By.XPATH, "//button/i").click()
    self.driver.find_element(By.ID, "txtIdAssignedDate").click()
    self.driver.find_element(By.ID, "txtIdAssignedDate").send_keys("2022-12-30")
    self.driver.find_element(By.XPATH, "//input[@type=\'number\']").click()
    self.driver.find_element(By.XPATH, "//input[@type=\'number\']").send_keys("6")
    self.driver.find_element(By.CSS_SELECTOR, ".col-lg-3:nth-child(4) .floating-input").click()
    self.driver.find_element(By.CSS_SELECTOR, ".col-lg-3:nth-child(4) .floating-input").send_keys("5")
    self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()
  
