# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestHCM():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_login(self):
    self.driver.get("http://192.168.6.103:7070/HCM/")
    self.driver.set_window_size(1366, 728)
    self.driver.find_element(By.CSS_SELECTOR, ".form-group:nth-child(1) > .form-control").click()
    self.driver.find_element(By.XPATH, "//input").send_keys("Admin")
    self.driver.find_element(By.CSS_SELECTOR, ".form-group:nth-child(2) > .form-control").click()
    self.driver.find_element(By.XPATH, "//div[2]/input").send_keys("Newpass2@")
    self.driver.find_element(By.CSS_SELECTOR, ".ng-input > input").click()
    self.driver.find_element(By.XPATH, "//span[contains(.,\'VS001\')]").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
  
  def test_searchDatainGradeMaster(self):
    self.driver.get("http://192.168.6.103:7070/HCM/")
    self.driver.set_window_size(1366, 728)
    self.driver.find_element(By.CSS_SELECTOR, ".form-group:nth-child(1) > .form-control").click()
    self.driver.find_element(By.XPATH, "//input").send_keys("Admin")
    self.driver.find_element(By.CSS_SELECTOR, ".form-group:nth-child(2) > .form-control").click()
    self.driver.find_element(By.XPATH, "//div[2]/input").send_keys("Newpass2@")
    self.driver.find_element(By.CSS_SELECTOR, ".ng-input > input").click()
    self.driver.find_element(By.XPATH, "//span[contains(.,\'VS001\')]").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
    self.driver.find_element(By.LINK_TEXT, "Personal Information Systems").click()
    self.driver.find_element(By.LINK_TEXT, "Grade Master").click()
    self.driver.find_element(By.CSS_SELECTOR, "input").click()
    self.driver.find_element(By.CSS_SELECTOR, "input").send_keys("engineer")
    self.driver.find_element(By.CSS_SELECTOR, "input").click()
  
  def test_searchDatainDesignationMaster(self):
    self.driver.get("http://192.168.6.103:7070/HCM/")
    self.driver.set_window_size(1366, 728)
    self.driver.find_element(By.CSS_SELECTOR, ".form-group:nth-child(1) > .form-control").click()
    self.driver.find_element(By.XPATH, "//input").send_keys("Admin")
    self.driver.find_element(By.CSS_SELECTOR, ".form-group:nth-child(2) > .form-control").click()
    self.driver.find_element(By.XPATH, "//div[2]/input").send_keys("Newpass2@")
    self.driver.find_element(By.CSS_SELECTOR, ".ng-input > input").click()
    self.driver.find_element(By.XPATH, "//span[contains(.,\'VS001\')]").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
    self.driver.find_element(By.CSS_SELECTOR, ".has-sub:nth-child(2) > .ng-tns-c152-3 > .menu-title").click()
    self.driver.find_element(By.CSS_SELECTOR, ".ng-tns-c152-3:nth-child(2) > .menu-content > .ng-tns-c152-3:nth-child(2) .menu-title").click()
    self.driver.find_element(By.CSS_SELECTOR, "input").click()
    self.driver.find_element(By.CSS_SELECTOR, "input").send_keys("assistant")
    self.driver.find_element(By.CSS_SELECTOR, "input").click()
  
  def test_searchDatainTeamMaster(self):
    self.driver.get("http://192.168.6.103:7070/HCM/")
    self.driver.set_window_size(1366, 728)
    self.driver.find_element(By.CSS_SELECTOR, ".form-group:nth-child(1) > .form-control").click()
    self.driver.find_element(By.XPATH, "//input").send_keys("Admin")
    self.driver.find_element(By.CSS_SELECTOR, ".form-group:nth-child(2) > .form-control").click()
    self.driver.find_element(By.XPATH, "//div[2]/input").send_keys("Newpass2@")
    self.driver.find_element(By.CSS_SELECTOR, ".ng-input > input").click()
    self.driver.find_element(By.XPATH, "//span[contains(.,\'VS001\')]").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
    self.driver.find_element(By.CSS_SELECTOR, ".has-sub:nth-child(2) > .ng-tns-c152-3 > .menu-title").click()
    self.driver.find_element(By.LINK_TEXT, "Team Master").click()
    self.driver.find_element(By.CSS_SELECTOR, "input").click()
    self.driver.find_element(By.CSS_SELECTOR, "input").send_keys("wings")
    self.driver.find_element(By.CSS_SELECTOR, "input").click()
  
  def test_searchDatainLeaveTypeMaster(self):
    self.driver.get("http://192.168.6.103:7070/HCM/")
    self.driver.set_window_size(1366, 728)
    self.driver.find_element(By.CSS_SELECTOR, ".form-group:nth-child(1) > .form-control").click()
    self.driver.find_element(By.XPATH, "//input").send_keys("Admin")
    self.driver.find_element(By.CSS_SELECTOR, ".form-group:nth-child(2) > .form-control").click()
    self.driver.find_element(By.XPATH, "//div[2]/input").send_keys("Newpass2@")
    self.driver.find_element(By.CSS_SELECTOR, ".ng-input > input").click()
    self.driver.find_element(By.XPATH, "//span[contains(.,\'VS001\')]").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
    self.driver.find_element(By.CSS_SELECTOR, ".has-sub:nth-child(2) > .ng-tns-c152-3 > .menu-title").click()
    self.driver.find_element(By.CSS_SELECTOR, ".ng-tns-c152-3:nth-child(2) > .menu-content > .ng-tns-c152-3:nth-child(7) .menu-title").click()
    self.driver.find_element(By.CSS_SELECTOR, "input").click()
    self.driver.find_element(By.CSS_SELECTOR, "input").send_keys("SICK")
    self.driver.find_element(By.CSS_SELECTOR, "input").click()
  
  def test_searchDatainLeaveRules(self):
    self.driver.get("http://192.168.6.103:7070/HCM/")
    self.driver.set_window_size(1366, 728)
    self.driver.find_element(By.CSS_SELECTOR, ".form-group:nth-child(1) > .form-control").click()
    self.driver.find_element(By.XPATH, "//input").send_keys("Admin")
    self.driver.find_element(By.CSS_SELECTOR, ".form-group:nth-child(2) > .form-control").click()
    self.driver.find_element(By.XPATH, "//div[2]/input").send_keys("Newpass2@")
    self.driver.find_element(By.CSS_SELECTOR, ".ng-input > input").click()
    self.driver.find_element(By.XPATH, "//span[contains(.,\'VS001\')]").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
    self.driver.find_element(By.LINK_TEXT, "Personal Information Systems").click()
    self.driver.find_element(By.XPATH, "//span[contains(.,\'Leave Rules\')]").click()
    self.driver.find_element(By.CSS_SELECTOR, "input").click()
    self.driver.find_element(By.CSS_SELECTOR, "input").send_keys("rest")
    self.driver.find_element(By.CSS_SELECTOR, "input").click()
  
